---
name: Docker Build and Push to ECR
description: Build a Docker image and push it to Amazon ECR

inputs:
  aws-account-id:
    description: AWS account ID
    required: true

  aws-region:
    description: AWS region
    required: true

  ecr-repo:
    description: ECR repository name
    required: true

  dockerfile:
    description: Path to Dockerfile
    required: false
    default: Dockerfile

  context:
    description: Docker build context
    required: false
    default: .

outputs:
  image-uri:
    description: Full ECR image URI with tag
    value: ${{ steps.build.outputs.image_uri }}

runs:
  using: composite
  steps:
    - name: Build and push image
      id: build
      shell: bash
      run: |
        set -ex

        IMAGE_TAG="${GITHUB_SHA::7}"
        ECR_URI="${{ inputs.aws-account-id }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repo }}"
        IMAGE_URI="$ECR_URI:$IMAGE_TAG"

        echo "Building image: $IMAGE_URI"

        docker build \
          -f "${{ inputs.dockerfile }}" \
          -t "$IMAGE_URI" \
          "${{ inputs.context }}"

        docker push "$IMAGE_URI"

        echo "image_uri=$IMAGE_URI" >> "$GITHUB_OUTPUT"

